In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn as skl
import plotly.express as px
from sklearn import neighbors
from sklearn.model_selection import train_test_split
from scipy import stats
from sklearn.preprocessing import StandardScaler
from sklearn import metrics
# stats.mode(keepdims=True)
scalar = StandardScaler()

In [5]:
raisin_path = 'dataset.csv'
df = pd.read_csv(raisin_path)
df

,label,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12
0,0,0,-812.031041,-403.644799,0,-863.459827,656.225068,0,-475.999951,7354.603422,1,25.007311,798.735432,0
1,0,0,-825.847440,-403.546154,0,-864.822550,576.230272,0,-475.999951,18986.319032,1,25.005396,798.735013,1
2,1,1,-827.553668,-400.176589,1,-863.900226,567.880530,1,-475.999934,13489.063167,0,25.004502,799.013262,1
3,0,0,-833.587169,-403.494321,0,-864.077237,563.387212,1,-475.999936,23165.546854,1,25.001330,799.020231,0
4,0,0,-826.119170,-402.117452,1,-865.356792,612.995258,0,-475.999956,24569.845448,1,25.005760,798.732774,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0,0,-829.247909,-401.067501,1,-864.735834,574.969988,0,-475.999974,33301.009052,0,25.005430,799.017807,0
183,1,1,-823.958587,-400.205432,0,-863.704586,559.603616,1,-476.054835,27201.566759,0,25.001779,799.288848,0
184,1,1,-827.832267,-399.845597,1,-865.930687,681.668195,0,-475.999996,5119.175604,0,25.004219,799.295938,1
185,0,0,-827.221473,-402.120409,1,-864.492868,581.301254,0,-475.999986,29949.234786,1,25.119782,799.009771,0
186,0,0,-825.507339,-403.694939,0,-864.947802,694.713427,0,-475.945118,34923.640543,0,25.008587,798.736539,0

In [12]:
train_df.loc[:, df.columns != 'label']

,col0,col1,col2,col3,col4,col5,col6,col7,col8,col9,col10,col11,col12
0,0,-812.031041,-403.644799,0,-863.459827,656.225068,0,-475.999951,7354.603422,1,25.007311,798.735432,0
1,0,-825.847440,-403.546154,0,-864.822550,576.230272,0,-475.999951,18986.319032,1,25.005396,798.735013,1
2,1,-827.553668,-400.176589,1,-863.900226,567.880530,1,-475.999934,13489.063167,0,25.004502,799.013262,1
3,0,-833.587169,-403.494321,0,-864.077237,563.387212,1,-475.999936,23165.546854,1,25.001330,799.020231,0
4,0,-826.119170,-402.117452,1,-865.356792,612.995258,0,-475.999956,24569.845448,1,25.005760,798.732774,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,-826.174706,-400.058683,0,-864.085225,652.269433,0,-475.999994,977.366077,0,25.003220,799.013900,0
96,1,-829.268156,-401.110661,1,-864.410017,652.547734,1,-475.999966,15263.106452,1,25.006145,799.005697,0
97,1,-812.433004,-401.969003,1,-864.392144,688.711295,0,-475.999977,661.915252,1,24.888911,799.297674,0
98,0,-817.193221,-403.537191,0,-865.447309,564.192602,1,-475.999976,10515.488224,1,25.001612,799.290928,1
99,1,-810.889451,-401.051900,0,-865.934474,602.734007,0,-475.999943,13618.963049,1,25.000655,798.727268,0

In [25]:
# features = ['major_axis_length', 'minor_axis_length', 'extent', 'perimeter']
# labels = ['label']
# X = df[features]
# y = df[labels]

# scalar.fit(df[features])
# X_train, X_test, y_train, y_test = train_test_split(scalar.transform(X), y, test_size=0.5)

# model = neighbors.KNeighborsClassifier(n_neighbors=7)
# model.fit(X_train, y_train.values.reshape(-1))

# preditions = model.predict(X_test)
# # preditions[:10]
# model.score(X_test, y_test.values)

# metrics.cohen_kappa_score(y_test, preditions)


# Read in dataset
df = pd.read_csv('dataset.csv')

# Split the data into training and testing sets
train_df = df.iloc[:100]
test_df = df.iloc[100:]

scalar = StandardScaler()
scalar.fit(train_df.loc[:, df.columns != 'label'])

# Standardize training data
train_X = scalar.transform(train_df.loc[:, df.columns != 'label'])
train_y = train_df['label']

# Standardize testing data
test_X = scalar.transform(test_df.loc[:, df.columns != 'label'])
test_y = test_df['label']

# Train model and test
model = neighbors.KNeighborsClassifier(n_neighbors=7)
model.fit(train_X, train_y.values.reshape(-1))
predictions = model.predict(test_X)

# Calculate accuracy (Cohen's kappa, in this case)
# Could be done like this if you left the `label` column in `test_df`
#   -- though of course the label must be absent from train_X and test_X!
acc = metrics.cohen_kappa_score(test_df.label, predictions)
acc

c:\Users\david\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

0.8620507399577166